### ISSUE TITLE
Hang/crash with NCCL

### ISSUE THREAD

**Issue by dlwh** [stanford-crfm/levanter#113]
See https://github.com/google/jax/issues/13559

**Comment by dlwh** [comment]
jag33 is working, so just need to try sphinxes

**Comment by julian-q** [comment]
I'm trying to get the example script from google/jax#13559 working on sphinx4 with 2 gpus, but it still crashes.
I installed JAX with this command:
```
pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
slurm command:
```bash
srun --account=nlp --cpus-per-task=2 --gres=gpu:2 \
    --job-name=quevedo-job-3787198 --mem=16G --nodelist=sphinx4 \
    --open-mode=append --partition=sphinx --time=14-0 \
    --ntasks=1 --nodes=1 --ntasks-per-node=1 --gpus-per-task=2 \
    bash run_jax_test.sh
```
Contents of run_jax_test.sh:
```bash
CONDA_EXE=/nlp/scr/quevedo/miniconda3/bin/conda
CONDA_PREFIX=/nlp/scr/quevedo/miniconda3/envs/levanter
CONDA_PROMPT_MODIFIER=(levanter)
_CE_CONDA=
CONDA_SHLVL=3
CONDA_PYTHON_EXE=/nlp/scr/quevedo/miniconda3/bin/python
CONDA_DEFAULT_ENV=levanter
CONDA_PREFIX_1=/sailhome/quevedo/miniconda3
CONDA_PREFIX_2=/nlp/scr/quevedo/miniconda3
PATH=/nlp/scr/quevedo/miniconda3/envs/levanter/bin:/sailhome/quevedo/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin:/u/nlp/bin:/sailhome/quevedo/.local/bin:/sailhome/quevedo/.fzf/bin:/u/nlp/bin:/sailhome/quevedo/.local/bin:/u/nlp/bin:/sailhome/quevedo/.local/bin
NCCL_DEBUG=TRACE

python jax_test.py \
&> $(hostname).log
```
Where `jax_test.py` is the example script.
I get the following error about replicated computations:
```
2023-04-23 21:12:33.876929: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2432] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.all_reduce' failed: external/xla/xla/service/gpu/nccl_all_reduce_thunk.cc:240: NCCL operation ncclAllReduce(it->send_buffer, it->recv_buffer, it->num_elements, it->dtype, reduce_op, comm, gpu_stream) failed: unhandled cuda error.
2023-04-23 21:12:33.876993: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2432] Execution of replica 1 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.all_reduce' failed: external/xla/xla/service/gpu/nccl_all_reduce_thunk.cc:240: NCCL operation ncclAllReduce(it->send_buffer, it->recv_buffer, it->num_elements, it->dtype, reduce_op, comm, gpu_stream) failed: unhandled cuda error.
[StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0), StreamExecutorGpuDevice(id=1, process_index=0, slice_index=0)]
1
Traceback (most recent call last):
  File "/sailhome/quevedo/jax_experiments/jax_test.py", line 20, in <module>
    r = jax.pmap(lambda x: jax.lax.psum(x, 'i'), axis_name='i')(xs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/quevedo/miniconda3/envs/levanter/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/quevedo/miniconda3/envs/levanter/lib/python3.11/site-packages/jax/_src/api.py", line 1861, in cache_miss
    out = map_bind_continuation(execute(*tracers))
                                ^^^^^^^^^^^^^^^^^
  File "/nlp/scr/quevedo/miniconda3/envs/levanter/lib/python3.11/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/quevedo/miniconda3/envs/levanter/lib/python3.11/site-packages/jax/_src/interpreters/pxla.py", line 1916, in __call__
    results = self.xla_executable.execute_sharded(input_bufs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.all_reduce' failed: external/xla/xla/service/gpu/nccl_all_reduce_thunk.cc:240: NCCL operation ncclAllReduce(it->send_buffer, it->recv_buffer, it->num_elements, it->dtype, reduce_op, comm, gpu_stream) failed: unhandled cuda error.: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sailhome/quevedo/jax_experiments/jax_test.py", line 20, in <module>
    r = jax.pmap(lambda x: jax.lax.psum(x, 'i'), axis_name='i')(xs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.all_reduce' failed: external/xla/xla/service/gpu/nccl_all_reduce_thunk.cc:240: NCCL operation ncclAllReduce(it->send_buffer, it->recv_buffer, it->num_elements, it->dtype, reduce_op, comm, gpu_stream) failed: unhandled cuda error.: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
```

**Comment by dlwh** [comment]
Oof. Do you get this failure on jags too?

**Comment by julian-q** [comment]
I'll hopefully try this later today

**Comment by julian-q** [comment]
Yes, I get the same error on jag33 with two GPUs @dlwh 
slurm command:
```bash
srun --account=nlp --cpus-per-task=2 --gres=gpu:2 \
    --job-name=quevedo-job-2217554 --mem=16G --nodelist=jagupard33 \
    --open-mode=append --partition=jag-standard --time=14-0 \
    --ntasks=1 --nodes=1 --ntasks-per-node=1 --gpus-per-task=2 \
    bash run_jax_test.sh
```

**Comment by dlwh** [comment]
this worked for me (note jag31, 33 is busy):

```
srun --account=nlp --cpus-per-task=2 --gres=gpu:2 --job-name=dlwh-job-2284557 --mem=16G --nodelist=jagupard31 --open-mode=append --partition=jag-standard --time=14-0 --pty bash jax_gpu.sh
```

**Comment by julian-q** [comment]
Sweet, I got the script working with multi-GPU on a sphinx! I installed JAX using
```bash
pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
and ran this slurm command.
```bash
srun --account=nlp --cpus-per-task=2 --gres=gpu:2 --job-name=quevedo-job-2284557 --mem=16G --nodelist=sphinx8 --open-mode=append --partition=sphinx --time=14-0 --pty bash run_jax_test.sh
```
At first, I got this error complaining about a mismatch in toolkit versions? I wasn't sure which versions it was referring to, since `nvidia-smi` showed that I had CUDA 11.5. However, it told me to add that flag, and that fixed it!
```
2023-05-02 15:08:43.208417: E external/xla/xla/service/gpu/gpu_compiler.cc:1592] The CUDA linking API did not work. Please use XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1 to bypass it, but expect to get longer compilation time due to the lack of multi-threading. Original error: INTERNAL: nvlink exited with non-zero error code 256, output: nvlink fatal   : Input file '/tmp/quevedo/tempfile-jagupard31.stanford.edu-194ceb5c-1552855-5fabd2eb93923.cubin' newer than toolkit (118 vs 111)
```
The script looks like this now
```bash
CONDA_EXE=/nlp/scr/quevedo/miniconda3/bin/conda
CONDA_PREFIX=/nlp/scr/quevedo/miniconda3/envs/levanter
CONDA_PROMPT_MODIFIER=(levanter)
_CE_CONDA=
CONDA_SHLVL=3
CONDA_PYTHON_EXE=/nlp/scr/quevedo/miniconda3/bin/python
CONDA_DEFAULT_ENV=levanter
CONDA_PREFIX_1=/sailhome/quevedo/miniconda3
CONDA_PREFIX_2=/nlp/scr/quevedo/miniconda3
PATH=/nlp/scr/quevedo/miniconda3/envs/levanter/bin:/sailhome/quevedo/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/puppetlabs/bin:/u/nlp/bin:/sailhome/quevedo/.local/bin:/sailhome/quevedo/.fzf/bin:/u/nlp/bin:/sailhome/quevedo/.local/bin:/u/nlp/bin:/sailhome/quevedo/.local/bin
NCCL_DEBUG=TRACE
XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1

python jax_test.py \
&> $(hostname).log
```
