### ISSUE TITLE
Run on H100 cluster "slurm+enroot+pyxis"

### ISSUE THREAD

**Issue by DwarKapex** [stanford-crfm/levanter#363]
I tried to run [ghcr.io/dlwh/levanter-cuda-cache:latest](http://ghcr.io/dlwh/levanter-cuda-cache:latest) from Oct 28, 2023 on cluster with H100s thru "slurm+enroot+pyxis". I came up with the following batch file:
```
#!/bin/bash

#SBATCH -A <account>
#SBATCH -p <partition>
#SBATCH -J levanter.test
#SBATCH -N 1
#SBATCH -t 00:05:00

CONT="ghcr.io#dlwh/levanter-cuda-cache:latest"

srun --ntasks-per-node=1 --container-image="$CONT" --mpi=pmi2 --export NCCL_DEBUG=TRACE --export WANDB_MODE=offline python -m levanter.main.train_lm --config /opt/levanter/config/gpt2_small_fast_wiki.yaml --trainer.per_device_parallelism 16 --trainer.train_batch_size 3
```

The issue I saw:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/levanter/src/levanter/main/train_lm.py", line 186, in <module>
    levanter.config.main(main)()
  File "/opt/levanter/src/levanter/config.py", line 84, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/opt/levanter/src/levanter/main/train_lm.py", line 77, in main
    config.trainer.initialize(config)
  File "/opt/levanter/src/levanter/trainer.py", line 533, in initialize
    self.distributed.initialize()
  File "/opt/levanter/src/levanter/distributed.py", line 248, in initialize
    device_ids = LevanterSlurmCluster.get_local_device_ids_for_process()
  File "/opt/levanter/src/levanter/distributed.py", line 108, in get_local_device_ids_for_process
    subprocess.check_output(["scontrol", "show", "hostnames", node_list], input=b"")
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'scontrol'
```
Looks like the train script thinks that it is run on the node and slurm API is available, but not inside the container.

**Comment by DwarKapex** [comment]
After updating, I run the same batch script with latest laventer docker from Nov 03, 2023. The previous problem was fixed, but now I see another one:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/levanter/src/levanter/main/train_lm.py", line 186, in <module>
    levanter.config.main(main)()
  File "/opt/levanter/src/levanter/config.py", line 84, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/opt/levanter/src/levanter/main/train_lm.py", line 77, in main
    config.trainer.initialize(config)
  File "/opt/levanter/src/levanter/trainer.py", line 533, in initialize
    self.distributed.initialize()
  File "/opt/levanter/src/levanter/distributed.py", line 276, in initialize
    device_ids = LevanterSlurmCluster.get_local_device_ids_for_process()
  File "/opt/levanter/src/levanter/distributed.py", line 111, in get_local_device_ids_for_process
    local_node_index = node_list.index(local_node)
ValueError: '<cluster-node>' is not in list
```
<cluster-node> is internal name of cluster node

**Comment by dlwh** [comment]
i'm having a lot of trouble getting anything multinode to work (jax or not) on our slurm cluster. would you do me a favor and send me a hello world jax thing that works for you?

**Comment by dlwh** [comment]
i got the clusters to detect, so i can mess with this a bit. I'd still like pointers on how you all run docker-on-slurm since i don't have a ton of experience with that.

**Comment by dlwh** [comment]
try one more time? i got rid of our custom SlurmCluster env detector for this branch to see if it that fixes for you, so now it's vanilla jax.distributed...

**Comment by DwarKapex** [comment]
JAX core container (`ghcr.io/nvidia/jax:<version>`) is a self contained. To test it, you can simple run `test-jax.sh` script:
```
test-jax.sh -b gpu
```

**Comment by dlwh** [comment]
Thanks, I was asking more for the slurm incantation, but I can see you all
have a fancy plug-in thing that we don’t have, so it wouldn’t translate
anyway.

**Comment by DwarKapex** [comment]
I was able to run it on a single node with 8xH100. Results looks reasonable:
```
wandb: Run summary:
wandb:                        backend gpu
wandb:                      eval/loss nan
wandb:                    global_step 199
wandb:                  learning_rate 0.0001
wandb:                    num_devices 8
wandb:                      num_hosts 1
wandb:                parameter_count 124439808
wandb:            throughput/duration 0.09157
wandb: throughput/examples_per_second 349.45657
wandb:           throughput/hook_time 0.00217
wandb:        throughput/loading_time 5e-05
wandb:   throughput/tokens_per_second 357843.52947
wandb:        throughput/total_tokens 6520832
wandb:                     train/loss nan
```

But with multinode run (2 nodes atually), I see this error:
```
2023-11-06 18:50:43,981 INFO worker.py:1664 -- Connected to Ray cluster. View the dashboard at ^[[1m^[[32m127.0.0.1:8265 ^[[39m^[[22m
2023-11-06 18:50:44,934 INFO node.py:1000 -- Can't find a `node_ip_address.json` file from /tmp/ray/session_2023-11-06_18-50-42_357600_1906786. Have you started Ray instsance using `ray start` or `ray.init`?
wandb: Tracking run with wandb version 0.15.12
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
2023-11-06T18:50:46 - 0 - levanter.data.shard_cache - shard_cache.py:970 - INFO :: Loading cache from cache/validation
2023-11-06T18:50:47 - 0 - levanter.data.shard_cache - shard_cache.py:970 - INFO :: Loading cache from cache/train
2023-11-06T18:50:47 - 0 - levanter.checkpoint - checkpoint.py:368 - WARNING :: No checkpoints found in checkpoints/ocykpdsx
2023-11-06T18:50:48 - 0 - __main__ - train_lm.py:134 - INFO :: No checkpoint found. Starting from scratch.
2023-11-06 18:50:54,945 INFO node.py:1000 -- Can't find a `node_ip_address.json` file from /tmp/ray/session_2023-11-06_18-50-42_357600_1906786. Have you started Ray instsance using `ray start` or `ray.init`?
2023-11-06 18:51:04,957 INFO node.py:1000 -- Can't find a `node_ip_address.json` file from /tmp/ray/session_2023-11-06_18-50-42_357600_1906786. Have you started Ray instsance using `ray start` or `ray.init`?
2023-11-06 18:51:14,968 INFO node.py:1000 -- Can't find a `node_ip_address.json` file from /tmp/ray/session_2023-11-06_18-50-42_357600_1906786. Have you started Ray instsance using `ray start` or `ray.init`?
2023-11-06 18:51:24,980 INFO node.py:1000 -- Can't find a `node_ip_address.json` file from /tmp/ray/session_2023-11-06_18-50-42_357600_1906786. Have you started Ray instsance using `ray start` or `ray.init`?
2023-11-06 18:51:34,991 INFO node.py:1000 -- Can't find a `node_ip_address.json` file from /tmp/ray/session_2023-11-06_18-50-42_357600_1906786. Have you started Ray instsance using `ray start` or `ray.init`?
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/levanter/src/levanter/main/train_lm.py", line 186, in <module>
    levanter.config.main(main)()
  File "/opt/levanter/src/levanter/config.py", line 84, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "/opt/levanter/src/levanter/main/train_lm.py", line 77, in main
    config.trainer.initialize(config)
  File "/opt/levanter/src/levanter/trainer.py", line 535, in initialize
    self.ray.initialize()
  File "/opt/levanter/src/levanter/distributed.py", line 288, in initialize
    auto_ray_cluster(address=self.address, start_workers=self.start_workers)
  File "/opt/levanter/src/levanter/distributed.py", line 233, in auto_ray_cluster
    ray.init(address=address, namespace=namespace, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 1629, in init
    _global_node = ray._private.node.Node(
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/node.py", line 199, in __init__
    node_ip_address = self._wait_and_get_for_node_address()
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/node.py", line 1007, in _wait_and_get_for_node_address
    raise ValueError(
ValueError: Can't find a `node_ip_address.json` file from /tmp/ray/session_2023-11-06_18-50-42_357600_1906786. for 60 seconds. A ray instance hasn't started. Did you do `ray start` or `ray.init` on this host?
2023-11-06 18:51:44,514 VINFO scripts.py:1085 -- Killed `^[[1m/usr/local/lib/python3.10/dist-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2023-11-06_18-50-42_312930_2583834/sockets/raylet --store_socket_
```

In multinode it was looking for a file `node_ip_address.json`. I assume, that it contains some information about nodes involved in the compute. 
Btw, what is `Ray`?

**Comment by dlwh** [comment]
hrm, ok, that's something.

Ray is a distributed computing framework (https://www.ray.io/). We use it for preprocessing, but we shouldn't need it for this test. (I don't know what's going on but we can cross that bridge we come to it.) Can you add `--trainer.ray.auto_start_cluster false` and see if that fixes?

**Comment by DwarKapex** [comment]
Interesting, I added the flag you mentioned above (to turn ray off). It helped with Ray error.
The output is a very curios reading:
```
train:   0%|          | 1/200 [01:24<4:40:36, 84.60s/it, loss=11]
train:   0%|          | 1/200 [01:24<4:2023-11-06T20:43:38 - 0 - levanter.callbacks - callbacks.py:57 - INFO :: validation loss: nan
train: 100%|██████████| 200/200 [01:45<02023-11-06T20:43:58 - 0 - levanter.callbacks - callbacks.py:57 - INFO :: validation loss: nan
wandb: Waiting for W&B process to finish... (success).s, loss=nan]
train: 100%|██████████| 200/200 [01:45<02023-11-06T20:43:58 - 0 - levanter.callbacks - callbacks.py:57 - INFO :: validation loss: nan
wandb: Waiting for W&B process to finish... (success).
wandb: - 0.000 MB of 0.000 MB uploaded (0.000 MB deduped)
wandb: Run history:
wandb:                    global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:                  learning_rate ▄███████▇▇▇▇▇▆▆▆▆▅▅▅▅▄▄▄▃▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁
wandb:            throughput/duration █▄▂▂▂▂▂▂▃▃▂▂▂▂▃▃▂▃▂▃▃▂▃▂▃▂▂▂▂▃▂▂▁▁▂▂▃▁▁▂
wandb: throughput/examples_per_second ▁▅▇▇▇▆▇▇▆▆▇▇▇▇▆▆▇▆▇▆▆▇▆▇▅▇▇▇▇▆▇▆▇█▇▇▆█▇▇
wandb:           throughput/hook_time █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:        throughput/loading_time ▂▂▂▁▁▂▂▁█▂▂▂█▁▁▇▂▇▂▃▂▂▂▂▂▂▂▂▂▁▂█▂▂▃▂▁▃▂▂
wandb:   throughput/tokens_per_second ▁▅▇▇▇▆▇▇▆▆▇▇▇▇▆▆▇▆▇▆▆▇▆▇▅▇▇▇▇▆▇▆▇█▇▇▆█▇▇
wandb:        throughput/total_tokens ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb: 
wandb: Run summary:
wandb:                        backend gpu
wandb:                      eval/loss nan
wandb:                    global_step 199
wandb:                  learning_rate 0.0001
wandb:                    num_devices 8
wandb:                      num_hosts 1
wandb:                parameter_count 124439808
wandb:            throughput/duration 0.09402
wandb: throughput/examples_per_second 340.36651
wandb:           throughput/hook_time 0.00177
wandb:        throughput/loading_time 5e-05
wandb:   throughput/tokens_per_second 348535.30354
wandb:        throughput/total_tokens 6520832
wandb:                     train/loss nan
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /opt/levanter/wandb/offline-run-20231106_204209-35lc1hod
wandb: Find logs at: ./wandb/offline-run-20231106_204209-35lc1hod/logs
wandb: WARNING Step only supports monotonically increasing values, use define_metric to set a custom x axis. For details see: https://wandb.me/define-metric
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'train/loss': nan, 'global_step': 199, '_timestamp': 1699332237.854266}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'learning_rate': 0.00010005665535572916, '_timestamp': 1699332237.8543367}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'eval/loss': nan, '_timestamp': 1699332238.0720947}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'throughput/total_tokens': 6520832, '_timestamp': 1699332238.0735772}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'throughput/examples_per_second': 340.3665073656403, 'throughput/tokens_per_second': 348535.30354241567, 'throughput/duration': 0.09401630098000169, '_timestamp': 1699332238.0736635}).
wandb: - 0.000 MB of 0.000 MB uploaded (0.000 MB deduped)
wandb: Run history:
wandb:                    global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:                  learning_rate ▄███████▇▇▇▇▇▆▆▆▆▅▅▅▅▄▄▄▃▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁
wandb:            throughput/duration █▂▃▃▁▂▂▂▂▂▂▃▃▂▃▃▃▄▃▂▂▃▃▄▃▂▂▂▁▃▂▂▂▃▂▂▃▂▂▂
wandb: throughput/examples_per_second ▁▆▆▆█▇▇▇▇▇▇▆▆▇▆▅▆▅▆▇▇▆▆▅▆▇▆▇▇▆▇▇▇▆▆▇▆▇▇▇
wandb:           throughput/hook_time █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:        throughput/loading_time ▂▃▂▂▁▂▂▁▂▂▃▂▃▃▃▃▂▃▃▃▂▂▃▃▃▂▂▃▂█▂▂▂▂▁▂▃▂▃▂
wandb:   throughput/tokens_per_second ▁▆▆▆█▇▇▇▇▇▇▆▆▇▆▅▆▅▆▇▇▆▆▅▆▇▆▇▇▆▇▇▇▆▆▇▆▇▇▇
wandb:        throughput/total_tokens ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb: 
wandb: Run summary:
wandb:                        backend gpu
wandb:                      eval/loss nan
wandb:                    global_step 199
wandb:                  learning_rate 0.0001
wandb:                    num_devices 8
wandb:                      num_hosts 1
wandb:                parameter_count 124439808
wandb:            throughput/duration 0.09375
wandb: throughput/examples_per_second 341.3267
wandb:           throughput/hook_time 0.00193
wandb:        throughput/loading_time 5e-05
wandb:   throughput/tokens_per_second 349518.53681
wandb:        throughput/total_tokens 6520832
wandb:                     train/loss nan
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /opt/levanter/wandb/offline-run-20231106_204209-dms9ouev
wandb: Find logs at: ./wandb/offline-run-20231106_204209-dms9ouev/logs
wandb: WARNING Step only supports monotonically increasing values, use define_metric to set a custom x axis. For details see: https://wandb.me/define-metric
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'train/loss': nan, 'global_step': 199, '_timestamp': 1699332238.3478193}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'learning_rate': 0.00010005665535572916, '_timestamp': 1699332238.347889}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'eval/loss': nan, '_timestamp': 1699332238.5657177}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'throughput/total_tokens': 6520832, '_timestamp': 1699332238.5671923}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'throughput/examples_per_second': 341.32669610108235, 'throughput/tokens_per_second': 349518.5368075083, 'throughput/duration': 0.09375182300573215, '_ti
```
1. Is this output expected?
2. I see 2 similar outputs like from single-node run. I expected to see some combined output: num_deviced = 16 or similar.

**Comment by dlwh** [comment]
Yeah I'd say they're not finding each other, which makes me think the SLURM
env variables aren't being set? Does the slurm auto-cluster stuff work
generally for you (in e.g. paxml)?

**Comment by yhtang** [comment]
This is a multi-node run of T5X on our CI cluster:
https://github.com/NVIDIA/JAX-Toolbox/blob/f6aff1635070d94afaa2afd775e4fba34185cdb1/.github/workflows/_test_t5x.yaml#L76C23-L76C23

**Comment by dlwh** [comment]
ok thanks! so looks like slurm discovery works for you with t5x. I don't really understand what's different. It should just be using the (same?) jax.distributed.init call?

I'll try to see what's going on on our end... we don't have pyxis and multinode is just totally broken on our cluster, so it's a bit of a pain to debug.

**Comment by DwarKapex** [comment]
I have 2 qq:
1. Is there a way to change the log level to get more messages in the stdout?
2. Here I do see that you call `jax.distributed.init` (https://github.com/stanford-crfm/levanter/blob/main/src/levanter/distributed.py#L253), but don't see related log message in output. For instance, in output stream I

**Comment by yhtang** [comment]
I'm trying to understanding how Levanter handles multi-node but it looks like the new container is built off a branch other than `main`, as in `main` we are still using `scontrol`. Could you please point me to the hotfix branch?

**Comment by DwarKapex** [comment]
Yu-Hang, I think the branch with fix is `fix_slurm_build`

**Comment by dlwh** [comment]
Thanks!

https://github.com/stanford-crfm/levanter/blob/fix_slurm_build/src/levanter/distributed.py#L253 is the branch as @DwarKapex says. I can force logger initialization to come before distributed.init

**Comment by dlwh** [comment]
rebuilding an image that sets INFO logging early

**Comment by DwarKapex** [comment]
Agree, that will be a long process. Run the latest one. The output is the same

**Comment by dlwh** [comment]
i just pushed another. I don't think it had been updated by the time you wrote? But I don't know if it's going to work better. still trying to get hello-world multinode to run

**Comment by DwarKapex** [comment]
OK, let take a closer look:
```
Running on hosts: <node1> <node2>
pyxis: imported docker image: ghcr.io#dlwh/levanter-cuda-cache:latest
pyxis: imported docker image: ghcr.io#dlwh/levanter-cuda-cache:latest
INFO:jax._src.distributed:JAX distributed initialized with visible devices: 0
INFO:jax._src.distributed:Connecting to JAX distributed service on <node1>:62634
INFO:jax._src.distributed:JAX distributed initialized with visible devices: 0
INFO:jax._src.distributed:Starting JAX distributed service on <node1>:62634
INFO:jax._src.distributed:Connecting to JAX distributed service on <node1>:62634
INFO:levanter.distributed:Initialized jax.distributed with 8 devices, 1 hosts, coordinator_address=None, process_id=None
INFO:levanter.distributed:Initialized jax.distributed with 8 devices, 1 hosts, coordinator_address=None, process_id=None
INFO:levanter.trainer:Setting run id to 2zp1ys3l
INFO:levanter.logging:Setting wandb code_dir to /opt/levanter
INFO:levanter.trainer:Setting run id to 6chr5bjy
INFO:levanter.logging:Setting wandb code_dir to /opt/levanter
```
Hm, interesting: according to logs, the second node was not involved at all, both runs happened on the the <node1>

**Comment by dlwh** [comment]
this makes me think that the SlurmCluster class isn't sniffing the env variables correctly? WDYT?

**Comment by dlwh** [comment]
@DwarKapex wait, just double checking, are you still doing -N 1?

**Comment by DwarKapex** [comment]
@dlwh, Nope, I'm doing `-N2`

**Comment by dlwh** [comment]
could you do the dumb thing of running `python -c "import jax; jax.distributed.initialize(); print(jax.devices())"` just so we can narrow it down

**Comment by yhtang** [comment]
This is what I found on a 2-node job on our CI cluster: (also note that we recommend 1 process per **GPU**, rather than 1 process per node)
```
$ salloc -N 2  --exclusive -t 04:00:00
$ srun --tasks-per-node=8  --gpus-per-node=8 --container-name=test --container-image=ghcr.io#dlwh/levanter-cuda-cache:latest bash -c 'echo $SLURM_STEP_NODELIST'
pyxis: imported docker image: ghcr.io#dlwh/levanter-cuda-cache:latest
pyxis: imported docker image: ghcr.io#dlwh/levanter-cuda-cache:latest
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
compute-permanent-node-[905,954]
$ srun --tasks-per-node=8  --gpus-per-node=8 --container-name=test --container-image=ghcr.io#dlwh/levanter-cuda-cache:latest python -c 'import jax.distributed; jax.distributed.initialize(); print(jax.devices());'
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
[cuda(id=0), cuda(id=1), cuda(id=2), cuda(id=3), cuda(id=4), cuda(id=5), cuda(id=6), cuda(id=7), cuda(id=8), cuda(id=9), cuda(id=10), cuda(id=11), cuda(id=12), cuda(id=13), cuda(id=14), cuda(id=15)]
```

Apparently, things appear fine on our CI cluster, but something went wrong when Vlad ran it on Eos.

**Comment by dlwh** [comment]
yep, i didn't realize that when i started, and i made a few assumptions that it was 1 process per node in a few places (mostly w/ ray though)

**Comment by dlwh** [comment]
(it is my stance that the slurm sniffer should work even if people do it the other way, fwiw)

**Comment by yhtang** [comment]
> (it is my stance that the slurm sniffer should work even if people do it the other way, fwiw)

agree

**Comment by DwarKapex** [comment]
Quick update/summary. 

The command below:

> $>  salloc -N 2 --exclusive -t 01:00:00
    $>  srun --tasks-per-node=8  --gpus-per-node=8 --container-name=test --container-image=ghcr.io#dlwh/levanter-cuda-cache:latest python -c 'import jax.distributed; jax.distributed.initialize(); print(jax.devices());'

showed that jax sees all 16 GPUs (see message from Yu-Hang above).

Today I run the similar cmd, but with levanter training:
```
$>  salloc -N 2 --exclusive -t 01:00:00
$> srun --tasks-per-node=8  --container-name=test --container-image=ghcr.io#dlwh/levanter-cuda-cache:latest python -m levanter.main.train_lm --config /opt/levanter/config/gpt2_small_fast_wiki.yaml --trainer.per_device_parallelism 1 --trainer.train_batch_size 32 --trainer.ray.auto_start_cluster false
```

The output is
```
INFO:levanter.distributed:Initialized jax.distributed with 8 devices, 1 hosts, coordinator_address=None, process_id=None
```

So, looks like levanter sees only 1 host with 8 GPUs, but jax sees all 16 GPUs

**Comment by DwarKapex** [comment]
We can reach the point, where I create a local repo that syncs with [git](https://github.com/stanford-crfm/levanter) automatically, build the docker, push to our local registry, run single-node test (to check it's not broken) and ping me to test it in multi-node env. 
Will that work?

**Comment by dlwh** [comment]
wait, is it significant that you left out `--gpus-per-node=8` in the second run?

**Comment by dlwh** [comment]
ugh, i think i figured it out. jax.devices() is getting called at the top level in a random script i left hanging out in the src directory, and it's getting invoked before jax.distributed.initialize is called, which ruins it.

**Comment by dlwh** [comment]
can you try ghcr.io/dlwh/levanter-cuda-cache:2023-11-14.2 . I think it might be ok, but slurm is being weird on my end.

**Comment by DwarKapex** [comment]
Looks like the last container works:
```
wandb: Run summary:
wandb:                        backend gpu
wandb:                      eval/loss nan
wandb:                    global_step 199
wandb:                    num_devices 16
wandb:                      num_hosts 16
wandb:            optim/learning_rate 0.0001
wandb:                parameter_count 124439808
wandb:            throughput/duration 0.0608
wandb: throughput/examples_per_second 526.30307
wandb:           throughput/hook_time 0.00239
wandb:        throughput/loading_time 2e-05
wandb:   throughput/tokens_per_second 538934.33868
wandb:        throughput/total_tokens 6520832
wandb:                     train/loss nan
wandb: 
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /opt/levanter/wandb/offline-run-20231115_130958-iupzsad2
wandb: Find logs at: ./wandb/offline-run-20231115_130958-iupzsad2/logs
wandb: WARNING Step only supports monotonically increasing values, use define_metric to set a custom x axis. For details see: https://wandb.me/define-metric
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'train/loss': nan, 'global_step': 199, '_timestamp': 1700082628.9168425}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'optim/learning_rate': 0.00010005665535572916, '_timestamp': 1700082628.9169188}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'eval/loss': nan, '_timestamp': 1700082629.0368288}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'throughput/total_tokens': 6520832, '_timestamp': 1700082629.03706}).
wandb: WARNING (User provided step: 199 is less than current step: 200. Dropping entry: {'throughput/examples_per_second': 526.303065112598, 'throughput/tokens_per_second': 538934.3386753004, 'throughput/duration': 0.0608014699537307, '_timestamp': 1700082629.0371096}).
```

**Comment by dlwh** [comment]
Nan train loss is worrying though

**Comment by dlwh** [comment]
ok i think we're declaring victory here?!?!?
